language: java
jdk:
  - oraclejdk8
env:
  global:
    - DOXYGEN_VERSION=1.8.15
git:
  depth: false

addons:
  apt:
    packages:
      - graphviz
      #- doxygen
      #- doxygen-doc
      #- doxygen-latex
      #- doxygen-gui
    update: true
  sonarcloud:
    organization: "fermod-github"
    token:
      secure: "$SONAR_TOKEN"

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.sonar/cache

before_script:
  # Manually install doxygen, because older versions throw errors on markdown code with images inside 
  # links (like the build status in the README) and it's the only way to get a newer doxygen in Ubuntu
  - if [ "$TRAVIS_BRANCH" = master ]; then ./scripts/install-doxygen.sh; fi

script:
  - git fetch --tags
  # The following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar

before_deploy:
  - if [ "$TRAVIS_BRANCH" = master ]; then ./scripts/generate-docs.sh; fi
  - if [ -n "$TRAVIS_TAG" ]; then ./scripts/generate-release.sh; fi
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: target/event-dispatcher-*.jar
    skip_cleanup: true
    prerelease: true
    overwrite: true
    draft: true
    name: "$RELEASE_NAME"
    # body: $RELEASE_BODY
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: master
