language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - .autoconf
    - $HOME/.m2
  
addons:
  apt:
    packages:
      - graphviz
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
    update: true
    
before_deploy:
  - cd doxygen
  - bash ./generate_docs.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
