language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - .autoconf
    - $HOME/.m2
git:
  depth: false
env:
  global:
    - DOXYGEN_PATH=$HOME/doxygen
    - DOXYGEN_VERSION=1.8.15
    # - DOXYGEN_BINPATH=${DOXYGEN_PATH}/${DOXYGEN_VERSION}/bin

before_script:
  - ./scripts/install-doxygen.sh

install:
  # Manually install doxygen, because older versions throw errors on markdown code with
  # images inside links (like the build status in the README) and it's the only way to get a newer
  # doxygen in Ubuntu
  - bash ./scripts/install-doxygen.sh
addons:
  apt:
    packages:
      - graphviz
      #- doxygen
      #- doxygen-doc
      #- doxygen-latex
      #- doxygen-gui
    update: true

before_deploy:
  - bash ./deploy-docs.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
