language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - .autoconf
    - $HOME/.m2

env:
  global:
    - DOXYGEN_PATH=$HOME/doxygen
    # - DOXYGEN_VERSION=doxygen-1.8.15
    # - DOXYGEN_BINPATH=${DOXYGEN_PATH}/${DOXYGEN_VERSION}/bin

before_install:
  - bash ./install-doxygen.sh
  # Install doxygen from binary, because older versions throw errors on markdown code with
  # images inside links (like the build status in the README) and it's the only way to get a newer
  # doxygen in Ubuntu
  # - if [ ! -e "${DOXYGEN_BINPATH}/doxygen" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
  #     mkdir -p ${DOXYGEN_PATH};
  #     wget http://doxygen.nl/files/${DOXYGEN_VERSION}.linux.bin.tar.gz;
  #     tar xvz ${DOXYGEN_VERSION}.linux.bin.tar.gz;
  #   fi
  # - export PATH=$PATH:${DOXYGEN_BINPATH}  
addons:
  apt:
    packages:
      - graphviz
      #- doxygen
      #- doxygen-doc
      #- doxygen-latex
      #- doxygen-gui
    update: true

before_deploy:
  - bash ./deploy_docs.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
