language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2

before_install:
  - sudo apt-get update
  - sudo apt-get install graphviz
  - sudo apt-get install doxygen
    
before_deploy:
  - cd doxygen
  - bash ./generate_docs.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
