language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - .autoconf
    - $HOME/.m2
env:
  global:
    - DOXYGEN_VERSION=doxygen-1.8.15
    
before_install:
  # Install doxygen from binary, because older versions throw errors on markdown code with
  # images inside links (like the build status in the README) and it's the only way to get a newer
  # doxygen in Ubuntu
  - if [ ! -e "$DOXY_BINPATH/doxygen" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      mkdir -p $HOME/doxygen;
      wget -qO- http://doxygen.nl/files/${DOXYGEN_VERSION}.linux.bin.tar.gz | tar xvz - -C $HOME/doxygen;
    fi
  - export PATH=$PATH:$HOME/doxygen/${DOXYGEN_VERSION}/bin  
addons:
  apt:
    packages:
      - graphviz
      #- doxygen
      #- doxygen-doc
      #- doxygen-latex
      #- doxygen-gui
    update: true

    
before_deploy:
  - cd doxygen
  - bash ./generate_docs.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
